services:
  localstack:
    container_name: localstack
    hostname: localstack
    image: localstack/localstack:4.13
    environment:
      - SERVICES=bedrock,bedrockruntime
      - DEBUG=1
    ports:
      - 4566:4566